In [149]:
import os, sys
import polars as pl

In [150]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..', '..')
data_dir = os.path.join(project_path, 'data', 'forms')
raw_data_dir = os.path.join(data_dir, 'raw_data')
processed_data_dir = os.path.join(data_dir, 'processed_data')

raw_data_filenames = [f for f in os.listdir(raw_data_dir) if 'forms' in f]

In [151]:
raw_data = {f.split('.')[0]: pl.read_csv(os.path.join(raw_data_dir, f)) for f in raw_data_filenames}


---

In [152]:
# Nomenclatura:
# tc = test conocimiento
# ta = test autoeficacia
# tcc = test carga congnitiva

# Global Variables
TC_TIPOS = ['retencion', 'transferencia']
PERIODOS = ['pre', 'post']
MAX_PUNTUACION_TC = 10
MAX_PUNTUACION_TC_TIPO = 5
MAX_PUNTUACION_TA = 7
MAX_PUNTUACION_TA = 10
TC_RESPUESTAS_CORRECTAS = {

    'pre': {

        'retencion': [
            'Describir y resumir un conjunto de datos recogidos sin sacar conclusiones sobre una población más amplia.',
            'Coche',
            6,
            'La distancia media aproximada entre cada dato concreto y la media del conjunto.',
            'Para analizar y comparar la relación entre dos variables categóricas simultáneamente.'
        ],

        'transferencia': [
            'La mediana, porque es resistente a los valores extremos y representa mejor al grupo mayoritario.',
            'Que el 50% de los alumnos sacó notas entre 50 y 80',
            'No, porque la estadística descriptiva sólo resume los datos recogidos (los 20 pacientes) sin sacar conclusiones de la población total.',
            'El Grupo B, porque sus valores están más dispersos y alejados de su media que los del Grupo A.',
            'Gráfico circular / tarta (Pie chart)'
        ]
    },

    'post': {

        'retencion': [
            'Resumir y describir los tiempos de esos 10 atletas específicamente.',
            'Rojo.',
            '25 m2 ambos.',
            'El grado medio de dispersión o separación de los valores alrededor de la media.',
            'Mostrar con qué frecuencia aparece cada valor distinto en una sola variable.'
        ],

        'transferencia': [
            'Porque la media será mucho más alta que el precio real de la mayoría de las casas debido al valor atípico.',
            'Que el 50% de los empleados tiene sueldos comprendidos entre 1500 € y 2500 €.',
            'No, la estadística descriptiva sólo describe el grupo analizado (Clase A); extenderlo a la Clase B sería inferencia.',
            'Ruta 2 tiene mayor desviación; es menos predecible y los datos están más lejos de la media.',
            'Un gráfico / diagrama de barras'
        ]
    }
}

In [153]:
def get_cols_tc(df):

    return {
        tc_tipo: [
            c for c in df.columns if 'conocimientos' in c and tc_tipo in c
        ] 
        for tc_tipo in TC_TIPOS
    }

def get_exprs_tc_tipos(cols_tc):

    return {
        periodo: {
            tc_tipo: [
                pl.col(c) == TC_RESPUESTAS_CORRECTAS[periodo][tc_tipo][i] 
                for i, c in enumerate(cols_tc[tc_tipo])
            ]
            for tc_tipo in TC_TIPOS
        } 
        for periodo in PERIODOS
    }

def get_cols_ta(df):

    return [
        c for c in df.columns if 'autoeficacia' in c
    ] 

def get_exprs_ta(cols_ta):

    return [
        pl.col(c) / MAX_PUNTUACION_TA
        for c in cols_ta
    ]

def get_cols_tcc_rel(df):

    return [
        c for c in df.columns if 'carga' in c and 'relevante' in c
    ] 

def get_exprs_tcc_rel(cols_tcc):

    return [
        pl.col(c) / MAX_PUNTUACION_TC
        for c in cols_tcc
    ]

def get_cols_tcc_int(df):

    return [
        c for c in df.columns if 'carga' in c and 'intrinseca' in c
    ] 

def get_exprs_tcc_int(cols_tcc):

    return [
        pl.col(c) / MAX_PUNTUACION_TC
        for c in cols_tcc
    ]


def get_cols_tcc_ext(df):

    return [
        c for c in df.columns if 'carga' in c and 'extrinseca' in c
    ] 

def get_exprs_tcc_ext(cols_tcc):

    return [
        pl.col(c) / MAX_PUNTUACION_TC
        for c in cols_tcc
    ]

In [156]:
def process_data(raw_data_dir, processed_data_dir):

    raw_data_filenames = [f for f in os.listdir(raw_data_dir) if 'forms' in f]

    raw_data = {f: pl.read_csv(os.path.join(raw_data_dir, f)) for f in raw_data_filenames}

    # TODO: eliminar cuando la función esté construida: 
    processed_data = {}

    for raw_filename, df_raw in raw_data.items():

        print(raw_filename)

        df = df_raw.clone()
        
        df = df.rename(
            {c: c.lower().replace('retención', 'retencion').replace('extrínseca', 'extrinseca').replace('intrínseca', 'intrinseca') for c in df.columns}
        ).rename({'identificador': 'id'})

        cols_tc = get_cols_tc(df)
        cols_ta = get_cols_ta(df)
        cols_tcc_rel = get_cols_tcc_rel(df)
        cols_tcc_int = get_cols_tcc_int(df)
        cols_tcc_ext = get_cols_tcc_ext(df)
        exprs_tc_tipos = get_exprs_tc_tipos(cols_tc)
        exprs_ta = get_exprs_ta(cols_ta)
        exprs_tcc_rel = get_exprs_tcc_rel(cols_tcc_rel)
        exprs_tcc_int = get_exprs_tcc_int(cols_tcc_int)
        exprs_tcc_ext = get_exprs_tcc_ext(cols_tcc_ext)
        exprs_tc_tipos = exprs_tc_tipos['pre'] if 'pre' in raw_filename else exprs_tc_tipos['post']

        df = (
                df\
                .with_columns(
                    [
                        pl.lit('pre').alias('periodo') if 'pre' in raw_filename else pl.lit('post').alias('periodo'),
                        (pl.col('puntuación').str.splitn(" / ", 2).struct.field("field_0").cast(pl.Int64) / MAX_PUNTUACION_TC).alias('puntuacion_tc'),
                        (pl.sum_horizontal(exprs_ta) / len(cols_ta)).round(2).alias('puntuacion_ta'),
                        (pl.sum_horizontal(exprs_tcc_rel) / len(cols_tcc_rel)).round(2).alias('puntuacion_tcc_rel') if 'post' in raw_filename else pl.lit(None).alias('puntuacion_tcc_rel'),
                        (pl.sum_horizontal(exprs_tcc_int) / len(cols_tcc_int)).round(2).alias('puntuacion_tcc_int') if 'post' in raw_filename else pl.lit(None).alias('puntuacion_tcc_int'),
                        (pl.sum_horizontal(exprs_tcc_ext) / len(cols_tcc_ext)).round(2).alias('puntuacion_tcc_ext') if 'post' in raw_filename else pl.lit(None).alias('puntuacion_tcc_ext')
                    ] + 
                    [
                        (pl.sum_horizontal(exprs_tc_tipos[tc_tipo]) / MAX_PUNTUACION_TC_TIPO).alias(f'puntuacion_tc_{tc_tipo}') for tc_tipo in TC_TIPOS
                    ]
                )
            )
                
        processed_data_path = os.path.join(processed_data_dir, f'processed_{raw_filename}')
        #df.write_csv(processed_data_path)

        # TODO: eliminar cuando la función esté construida: 
        processed_data[f'processed_{raw_filename}'] = df

    return processed_data

In [157]:
processed_data = process_data(raw_data_dir=raw_data_dir, processed_data_dir=processed_data_dir)

respuestas_forms_pre_RamiroMaeztu_20260218.csv
respuestas_forms_post_RamiroMaeztu_20260218.csv

In [158]:
processed_data['processed_respuestas_forms_pre_RamiroMaeztu_20260218.csv']

shape: (64, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ marca     ┆ puntuació ┆ id        ┆ [autoefic ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ puntuaci │
│ temporal  ┆ n         ┆ ---       ┆ acia      ┆   ┆ n_tcc_int ┆ n_tcc_ext ┆ n_tc_rete ┆ on_tc_tr │
│ ---       ┆ ---       ┆ str       ┆ inicial]  ┆   ┆ ---       ┆ ---       ┆ ncion     ┆ ansferen │
│ str       ┆ str       ┆           ┆ estoy s…  ┆   ┆ null      ┆ null      ┆ ---       ┆ cia      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 0.6      │
│ 6 9:03:26 ┆           ┆ ztu-9jg   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 5         ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 0.6      │
│ 6 9:03:39 ┆           ┆ ztu-unc   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ 0.8       ┆ 0.8      │
│ 6 9:04:29 ┆           ┆ ztu-wr6   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 0.6      │
│ 6 9:05:17 ┆           ┆ ztu-pu9   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 6 / 10    ┆ RamiroMae ┆ 5         ┆ … ┆ null      ┆ null      ┆ 0.6       ┆ 0.6      │
│ 6 9:05:30 ┆           ┆ ztu-8jb   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 18/02/202 ┆ 6 / 10    ┆ RamiroMae ┆ 5         ┆ … ┆ null      ┆ null      ┆ 0.4       ┆ 0.8      │
│ 6 9:57:22 ┆           ┆ ztu-scg   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 5 / 10    ┆ RamiroMae ┆ 4         ┆ … ┆ null      ┆ null      ┆ 0.8       ┆ 0.2      │
│ 6 9:57:51 ┆           ┆ ztu-8q1   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 2 / 10    ┆ RamiroMae ┆ 3         ┆ … ┆ null      ┆ null      ┆ 0.4       ┆ 0.0      │
│ 6 9:57:52 ┆           ┆ ztu-zhk   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 5 / 10    ┆ RamiroMae ┆ 3         ┆ … ┆ null      ┆ null      ┆ 0.8       ┆ 0.2      │
│ 6 9:57:59 ┆           ┆ ztu-qjr   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 3 / 10    ┆ RamiroMae ┆ 4         ┆ … ┆ null      ┆ null      ┆ 0.4       ┆ 0.2      │
│ 6 9:58:41 ┆           ┆ ztu-g49   ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [159]:
processed_data['processed_respuestas_forms_post_RamiroMaeztu_20260218.csv']

shape: (64, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ marca     ┆ puntuació ┆ id        ┆ [conocimi ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ puntuaci │
│ temporal  ┆ n         ┆ ---       ┆ entos     ┆   ┆ n_tcc_int ┆ n_tcc_ext ┆ n_tc_rete ┆ on_tc_tr │
│ ---       ┆ ---       ┆ str       ┆ post] [re ┆   ┆ ---       ┆ ---       ┆ ncion     ┆ ansferen │
│ str       ┆ str       ┆           ┆ tencio…   ┆   ┆ f64       ┆ f64       ┆ ---       ┆ cia      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.43      ┆ 0.27      ┆ 1.0       ┆ 1.0      │
│ 6 9:43:17 ┆           ┆ ztu-ks0   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.4       ┆ 0.27      ┆ 1.0       ┆ 1.0      │
│ 6 9:43:40 ┆           ┆ ztu-pu9   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.6       ┆ 0.47      ┆ 1.0       ┆ 1.0      │
│ 6 9:44:03 ┆           ┆ ztu-8jb   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 6 / 10    ┆ RamiroMae ┆ Demostrar ┆ … ┆ 0.53      ┆ 0.63      ┆ 0.4       ┆ 0.8      │
│ 6 9:44:57 ┆           ┆ ztu-x5e   ┆ por qué   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ unos      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ corren …  ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 9 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.3       ┆ 0.27      ┆ 1.0       ┆ 0.8      │
│ 6 9:45:32 ┆           ┆ ztu-80a   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 18/02/202 ┆ 9 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.23      ┆ 0.17      ┆ 0.8       ┆ 1.0      │
│ 6         ┆           ┆ ztu-qjr   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:22:55  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.37      ┆ 0.63      ┆ 0.6       ┆ 1.0      │
│ 6         ┆           ┆ ztu-8q1   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:23:28  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 7 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.3       ┆ 0.23      ┆ 0.6       ┆ 0.8      │
│ 6         ┆           ┆ ztu-9t2   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:23:28  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.13      ┆ 0.4       ┆ 0.8       ┆ 0.8      │
│ 6         ┆           ┆ ztu-byq   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:23:33  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 7 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ 0.3       ┆ 0.4       ┆ 0.8       ┆ 0.6      │
│ 6         ┆           ┆ ztu-scg   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:26:04  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

---