In [1]:
import os, sys
import polars as pl
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns 
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.diagnostic import het_breuschpagan
import numpy as np
import pyarrow as pa

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..', '..')
data_dir = os.path.join(project_path, 'data', 'forms')
raw_data_dir = os.path.join(data_dir, 'raw_data')
processed_data_dir = os.path.join(data_dir, 'processed_data')
hashes_dir = os.path.join(project_path, 'data', 'hashes', 'processed_data')
raw_data_filenames = [f for f in os.listdir(raw_data_dir) if 'forms' in f]

In [3]:
raw_data = {f.split('.')[0]: pl.read_csv(os.path.join(raw_data_dir, f)) for f in raw_data_filenames}
df_grupos = pl.read_csv(os.path.join(hashes_dir, "hashes_groups.csv"), separator=";")

In [4]:
sys.path.insert(0, project_path)
from src.utils.forms.forms_data_processing import (
    calcular_medias_puntuacion,
    get_cols_tc,
    get_cols_ta,
    get_cols_tcc_ext,
    get_cols_tcc_int,
    get_cols_tcc_rel,
    get_exprs_tc_tipos,
    get_exprs_ta,
    get_exprs_tcc_ext,
    get_exprs_tcc_int,
    get_exprs_tcc_rel,
    process_data,
    add_categorization,
    analyze_experiment_results,
    test_significacion_estadistica,
    analyze_experiment_results_centros,
    test_significacion_estadistica_centros,
    realizar_analisis_hake_normalizado,
    calcular_medias_puntuacion,
    realizar_analisis_hake_por_centro
)

from src.config.config_forms import (
    TC_TIPOS,
    PERIODOS,
    MAX_PUNTUACION_TC,
    MAX_PUNTUACION_TA,
    TC_RESPUESTAS_CORRECTAS,
    MAX_PUNTUACION_TC_TIPO
)


---

# Procesado Inicial

In [5]:
processed_data = process_data(raw_data_dir=raw_data_dir, processed_data_dir=processed_data_dir)

respuestas_forms_post.csv
respuestas_forms_pre.csv

In [6]:
processed_data['processed_respuestas_forms_pre.csv']

shape: (192, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ marca     ┆ puntuació ┆ id        ┆ [autoefic ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ indice_d │
│ temporal  ┆ n         ┆ ---       ┆ acia      ┆   ┆ n_tcc_rel ┆ n_tcc_int ┆ n_tcc_ext ┆ esempeño │
│ ---       ┆ ---       ┆ str       ┆ inicial]  ┆   ┆ _cat      ┆ _cat      ┆ _cat      ┆ _global  │
│ str       ┆ str       ┆           ┆ estoy s…  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ null      ┆ null      ┆ null      ┆ f32      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.5      │
│ 6 9:03:26 ┆           ┆ ztu-9jg   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 5         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.5      │
│ 6 9:03:39 ┆           ┆ ztu-unc   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.0      │
│ 6 9:04:29 ┆           ┆ ztu-wr6   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 8 / 10    ┆ RamiroMae ┆ 6         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.5      │
│ 6 9:05:17 ┆           ┆ ztu-pu9   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 6 / 10    ┆ RamiroMae ┆ 5         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.0      │
│ 6 9:05:30 ┆           ┆ ztu-8jb   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10/04/202 ┆ 5 / 10    ┆ Laguna-lq ┆ 6         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.0      │
│ 6 9:39:18 ┆           ┆ w         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 3 / 10    ┆ Laguna-zf ┆ 4         ┆ … ┆ null      ┆ null      ┆ null      ┆ 1.0      │
│ 6 9:39:40 ┆           ┆ a         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 7 / 10    ┆ Laguna-r4 ┆ 4         ┆ … ┆ null      ┆ null      ┆ null      ┆ 1.5      │
│ 6 9:40:13 ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 4 / 10    ┆ Laguna-p3 ┆ 5         ┆ … ┆ null      ┆ null      ┆ null      ┆ 1.0      │
│ 6 9:40:22 ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 5 / 10    ┆ Laguna-i9 ┆ 5         ┆ … ┆ null      ┆ null      ┆ null      ┆ 1.5      │
│ 6 9:40:28 ┆           ┆ p         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
processed_data['processed_respuestas_forms_post.csv']

shape: (192, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ marca     ┆ puntuació ┆ id        ┆ [conocimi ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ indice_d │
│ temporal  ┆ n         ┆ ---       ┆ entos     ┆   ┆ n_tcc_rel ┆ n_tcc_int ┆ n_tcc_ext ┆ esempeño │
│ ---       ┆ ---       ┆ str       ┆ post] [re ┆   ┆ _cat      ┆ _cat      ┆ _cat      ┆ _global  │
│ str       ┆ str       ┆           ┆ tencio…   ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ f32      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ Medio     ┆ Medio     ┆ Bajo      ┆ 2.0      │
│ 6 9:43:17 ┆           ┆ ztu-ks0   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ Bajo      ┆ Medio     ┆ Bajo      ┆ 2.5      │
│ 6 9:43:40 ┆           ┆ ztu-pu9   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 10 / 10   ┆ RamiroMae ┆ Resumir y ┆ … ┆ Bajo      ┆ Alto      ┆ Medio     ┆ 2.0      │
│ 6 9:44:03 ┆           ┆ ztu-8jb   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 6 / 10    ┆ RamiroMae ┆ Demostrar ┆ … ┆ Bajo      ┆ Alto      ┆ Alto      ┆ 1.0      │
│ 6 9:44:57 ┆           ┆ ztu-x5e   ┆ por qué   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ unos      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ corren …  ┆   ┆           ┆           ┆           ┆          │
│ 18/02/202 ┆ 9 / 10    ┆ RamiroMae ┆ Resumir y ┆ … ┆ Alto      ┆ Medio     ┆ Bajo      ┆ 2.5      │
│ 6 9:45:32 ┆           ┆ ztu-80a   ┆ describir ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10/04/202 ┆ 7 / 10    ┆ Laguna-r4 ┆ Resumir y ┆ … ┆ Bajo      ┆ Medio     ┆ Medio     ┆ 2.0      │
│ 6         ┆           ┆ 5         ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:21:28  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 7 / 10    ┆ Laguna-lq ┆ Resumir y ┆ … ┆ Alto      ┆ Alto      ┆ Bajo      ┆ 2.0      │
│ 6         ┆           ┆ w         ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:21:52  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 6 / 10    ┆ Laguna-ch ┆ Resumir y ┆ … ┆ Alto      ┆ Bajo      ┆ Medio     ┆ 2.0      │
│ 6         ┆           ┆ n         ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:22:10  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 8 / 10    ┆ Laguna-yn ┆ Calcular  ┆ … ┆ Alto      ┆ Alto      ┆ Alto      ┆ 2.5      │
│ 6         ┆           ┆ o         ┆ la probab ┆   ┆           ┆           ┆           ┆          │
│ 10:24:39  ┆           ┆           ┆ ilidad de ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ga…       ┆   ┆           ┆           ┆           ┆          │
│ 10/04/202 ┆ 9 / 10    ┆ Laguna-9w ┆ Resumir y ┆ … ┆ Bajo      ┆ Bajo      ┆ Bajo      ┆ 1.5      │
│ 6         ┆           ┆ q         ┆ describir ┆   ┆           ┆           ┆           ┆          │
│ 10:25:03  ┆           ┆           ┆ los       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tiempo…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df_post = processed_data['processed_respuestas_forms_post.csv']
df_pre = processed_data['processed_respuestas_forms_pre.csv']

In [10]:
# 1. Renombrar pre/post
cols_protegidas = ['id', 'centro']
df_pre_suf = df_pre.rename({col: f"{col}_pre" for col in df_pre.columns if col not in cols_protegidas})
df_post_suf = df_post.rename({col: f"{col}_post" for col in df_post.columns if col not in cols_protegidas})

# 2. Cruzar pre/post
df_cruzado = df_pre_suf.join(df_post_suf, on='id', how='inner')

# 3. Unir con la tabla de grupos
df_grupos = (
    pl.read_csv(os.path.join(hashes_dir, "hashes_groups.csv"), separator=";")
    .select(["id", "grupo"])
)

df_cruzado = df_cruzado.join(
    df_grupos,
    on="id",
    how="left"
)

---

## Comprobación de los IDs (**No ejecutar esta parte**)

In [37]:
df_grupos = (
    pl.read_csv(
        os.path.join(hashes_dir, "hashes_groups.csv"),
        separator=";"
    )
    .select("id")
    .unique()
)
ids_pre = df_pre.select("id").unique()
ids_post = df_post.select("id").unique()
ids_pre_sin_grupo = ids_pre.join(
    df_grupos,
    on="id",
    how="anti"
)
print("IDs en PRE que NO están en hashes_groups:")
print(ids_pre_sin_grupo)

ids_post_sin_grupo = ids_post.join(
    df_grupos,
    on="id",
    how="anti"
)

print("\nIDs en POST que NO están en hashes_groups:")
print(ids_post_sin_grupo)

IDs en PRE que NO están en hashes_groups:
shape: (0, 1)
┌─────┐
│ id  │
│ --- │
│ str │
╞═════╡
└─────┘

IDs en POST que NO están en hashes_groups:
shape: (1, 1)
┌──────────────────┐
│ id               │
│ ---              │
│ str              │
╞══════════════════╡
│ RamiroMaeztu-rya │
└──────────────────┘

In [38]:
ids_pre = df_pre.select("id").unique()
ids_post = df_post.select("id").unique()
ids_pre_no_post = ids_pre.join(
    ids_post,
    on="id",
    how="anti"
)
print("IDs que están en PRE pero NO en POST:")
print(ids_pre_no_post)

IDs que están en PRE pero NO en POST:
shape: (1, 1)
┌──────────────────┐
│ id               │
│ ---              │
│ str              │
╞══════════════════╡
│ RamiroMaeztu-kya │
└──────────────────┘

Hemos descubierto que uno de los estudiantes escribió erróneamente su ID, por lo que lo modificamos directamente

In [41]:
df_pre = df_pre.with_columns(
    pl.when(pl.col("id") == "RamiroMaeztu-rya")
    .then(pl.lit("RamiroMaeztu-kya"))
    .otherwise(pl.col("id"))
    .alias("id")
)

df_post = df_post.with_columns(
    pl.when(pl.col("id") == "RamiroMaeztu-rya")
    .then(pl.lit("RamiroMaeztu-kya"))
    .otherwise(pl.col("id"))
    .alias("id")
)

## Análisis lógica de resultados

In [11]:
# Columnas que queremos comparar
constructos = [
    "puntuacion_tc",
    "puntuacion_tc_retencion",
    "puntuacion_tc_transferencia",
    "puntuacion_ta",
    "indice_desempeño_global"
]

# Generamos las comparaciones POST >= PRE
comparaciones = [
    (pl.col(f"{c}_post") >= pl.col(f"{c}_pre")).alias(f"{c}_ok")
    for c in constructos
]

# Primero agregamos las columnas *_ok
df_check = df_cruzado.with_columns(comparaciones)

# Luego agregamos la columna resumen
df_check = df_check.with_columns(
    pl.all_horizontal([f"{c}_ok" for c in constructos]).alias("mejora_total")
)

# Mostrar individuos que NO mejoraron en todos los constructos
df_no_mejora = df_check.filter(pl.col("mejora_total") == False)

print("Individuos con alguna puntuación POST < PRE:")
print(
    df_no_mejora.select(
        ["id"] + [f"{c}_ok" for c in constructos]
    )
)

Individuos con alguna puntuación POST < PRE:
shape: (109, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ id             ┆ puntuacion_tc_ ┆ puntuacion_tc_ ┆ puntuacion_tc ┆ puntuacion_ta ┆ indice_desemp │
│ ---            ┆ ok             ┆ retencion_ok   ┆ _transferenci ┆ _ok           ┆ eño_global_ok │
│ str            ┆ ---            ┆ ---            ┆ a_ok          ┆ ---           ┆ ---           │
│                ┆ bool           ┆ bool           ┆ ---           ┆ bool          ┆ bool          │
│                ┆                ┆                ┆ bool          ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ RamiroMaeztu-8 ┆ true           ┆ true           ┆ true          ┆ false         ┆ true          │
│ jb             ┆                ┆                ┆               ┆               ┆               │
│ RamiroMaeztu-x ┆ true           ┆ false          ┆ true          ┆ false         ┆ false         │
│ 5e             ┆                ┆                ┆               ┆               ┆               │
│ RamiroMaeztu-8 ┆ true           ┆ true           ┆ true          ┆ true          ┆ false         │
│ 0a             ┆                ┆                ┆               ┆               ┆               │
│ RamiroMaeztu-4 ┆ true           ┆ true           ┆ true          ┆ false         ┆ true          │
│ 04             ┆                ┆                ┆               ┆               ┆               │
│ RamiroMaeztu-h ┆ true           ┆ true           ┆ true          ┆ true          ┆ false         │
│ rb             ┆                ┆                ┆               ┆               ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ Laguna-p3n     ┆ true           ┆ false          ┆ true          ┆ true          ┆ true          │
│ Laguna-r45     ┆ true           ┆ false          ┆ true          ┆ true          ┆ true          │
│ Laguna-chn     ┆ true           ┆ false          ┆ true          ┆ true          ┆ true          │
│ Laguna-yno     ┆ false          ┆ false          ┆ false         ┆ true          ┆ false         │
│ Laguna-9wq     ┆ false          ┆ true           ┆ false         ┆ false         ┆ false         │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [12]:
df_diferencias = df_cruzado.filter(pl.col("id") == "JoseGarciaNieto-wob")
df_diferencias.select([
    "puntuacion_tc_pre", "puntuacion_tc_retencion_pre", "puntuacion_tc_transferencia_pre",
    "puntuacion_ta_pre", "indice_desempeño_global_pre",
    "puntuacion_tc_post", "puntuacion_tc_retencion_post", "puntuacion_tc_transferencia_post",
    "puntuacion_ta_post", "indice_desempeño_global_post"
])

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ puntuacio ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ indice_d │
│ n_tc_pre  ┆ n_tc_rete ┆ n_tc_tran ┆ n_ta_pre  ┆   ┆ n_tc_rete ┆ n_tc_tran ┆ n_ta_post ┆ esempeño │
│ ---       ┆ ncion_pre ┆ sferencia ┆ ---       ┆   ┆ ncion_pos ┆ sferencia ┆ ---       ┆ _global_ │
│ f64       ┆ ---       ┆ _pr…      ┆ f64       ┆   ┆ t         ┆ _po…      ┆ f64       ┆ post     │
│           ┆ f64       ┆ ---       ┆           ┆   ┆ ---       ┆ ---       ┆           ┆ ---      │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.6       ┆ 0.8       ┆ 0.4       ┆ 0.4       ┆ … ┆ 0.8       ┆ 0.0       ┆ 0.68      ┆ 2.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
df_diferencias = df_cruzado.filter(pl.col("id") == "Laguna-wob")
df_diferencias.select([
    "puntuacion_tc_pre", "puntuacion_tc_retencion_pre", "puntuacion_tc_transferencia_pre",
    "puntuacion_ta_pre", "indice_desempeño_global_pre",
    "puntuacion_tc_post", "puntuacion_tc_retencion_post", "puntuacion_tc_transferencia_post",
    "puntuacion_ta_post", "indice_desempeño_global_post"
])

shape: (0, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ puntuacio ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ … ┆ puntuacio ┆ puntuacio ┆ puntuacio ┆ indice_d │
│ n_tc_pre  ┆ n_tc_rete ┆ n_tc_tran ┆ n_ta_pre  ┆   ┆ n_tc_rete ┆ n_tc_tran ┆ n_ta_post ┆ esempeño │
│ ---       ┆ ncion_pre ┆ sferencia ┆ ---       ┆   ┆ ncion_pos ┆ sferencia ┆ ---       ┆ _global_ │
│ f64       ┆ ---       ┆ _pr…      ┆ f64       ┆   ┆ t         ┆ _po…      ┆ f64       ┆ post     │
│           ┆ f64       ┆ ---       ┆           ┆   ┆ ---       ┆ ---       ┆           ┆ ---      │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Análisis diferencias por grupos

In [14]:
df_completo, tabla_resumen = analyze_experiment_results(processed_data, hashes_dir)

print("--- TABLA DE MÉTRICAS ---")
print(tabla_resumen)

test_significacion_estadistica(df_completo, metrica="puntuacion_tc")

--- TABLA DE MÉTRICAS ---
shape: (4, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ periodo ┆ grupo      ┆ puntuacio ┆ puntuacio ┆ … ┆ indice_de ┆ puntuacio ┆ puntuacio ┆ indice_de │
│ ---     ┆ ---        ┆ n_tc_medi ┆ n_tc_std  ┆   ┆ sempeño_g ┆ n_tc_var_ ┆ n_ta_var_ ┆ sempeño_g │
│ str     ┆ str        ┆ a         ┆ ---       ┆   ┆ lobal_std ┆ %         ┆ %         ┆ lobal_var │
│         ┆            ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ _%        │
│         ┆            ┆ f64       ┆           ┆   ┆ f32       ┆ f64       ┆ f64       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ f32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ post    ┆ control    ┆ 0.8       ┆ 0.16      ┆ … ┆ 0.6       ┆ 26.98     ┆ 18.6      ┆ 1.05      │
│ post    ┆ experiment ┆ 0.74      ┆ 0.18      ┆ … ┆ 0.58      ┆ 25.42     ┆ 11.11     ┆ -6.84     │
│         ┆ al         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ pre     ┆ control    ┆ 0.63      ┆ 0.18      ┆ … ┆ 0.59      ┆ null      ┆ null      ┆ null      │
│ pre     ┆ experiment ┆ 0.59      ┆ 0.18      ┆ … ┆ 0.6       ┆ null      ┆ null      ┆ null      │
│         ┆ al         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
--- Análisis Estadístico para: puntuacion_tc (Post-test) ---
Media Experimental: 0.74
Media Control: 0.80
P-valor: 0.0115
✅ CONCLUSIÓN: La diferencia ES estadísticamente significativa (p < 0.05). La IA tuvo un impacto real.

In [15]:
pl.Config.set_tbl_cols(-1)  # mostrar todas las columnas
print(tabla_resumen)

shape: (4, 11)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ period ┆ grupo  ┆ puntua ┆ puntua ┆ puntua ┆ puntua ┆ indice ┆ indice ┆ puntua ┆ puntua ┆ indice │
│ o      ┆ ---    ┆ cion_t ┆ cion_t ┆ cion_t ┆ cion_t ┆ _desem ┆ _desem ┆ cion_t ┆ cion_t ┆ _desem │
│ ---    ┆ str    ┆ c_medi ┆ c_std  ┆ a_medi ┆ a_std  ┆ peño_g ┆ peño_g ┆ c_var_ ┆ a_var_ ┆ peño_g │
│ str    ┆        ┆ a      ┆ ---    ┆ a      ┆ ---    ┆ lobal_ ┆ lobal_ ┆ %      ┆ %      ┆ lobal_ │
│        ┆        ┆ ---    ┆ f64    ┆ ---    ┆ f64    ┆ media  ┆ std    ┆ ---    ┆ ---    ┆ var_%  │
│        ┆        ┆ f64    ┆        ┆ f64    ┆        ┆ ---    ┆ ---    ┆ f64    ┆ f64    ┆ ---    │
│        ┆        ┆        ┆        ┆        ┆        ┆ f32    ┆ f32    ┆        ┆        ┆ f32    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ post   ┆ contro ┆ 0.8    ┆ 0.16   ┆ 0.51   ┆ 0.11   ┆ 1.92   ┆ 0.6    ┆ 26.98  ┆ 18.6   ┆ 1.05   │
│        ┆ l      ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ post   ┆ experi ┆ 0.74   ┆ 0.18   ┆ 0.5    ┆ 0.12   ┆ 1.77   ┆ 0.58   ┆ 25.42  ┆ 11.11  ┆ -6.84  │
│        ┆ mental ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ pre    ┆ contro ┆ 0.63   ┆ 0.18   ┆ 0.43   ┆ 0.14   ┆ 1.9    ┆ 0.59   ┆ null   ┆ null   ┆ null   │
│        ┆ l      ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ pre    ┆ experi ┆ 0.59   ┆ 0.18   ┆ 0.45   ┆ 0.12   ┆ 1.9    ┆ 0.6    ┆ null   ┆ null   ┆ null   │
│        ┆ mental ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [16]:
tabla_medias_post = calcular_medias_puntuacion(processed_data['processed_respuestas_forms_post.csv'], df_grupos)
tabla_medias_pre = calcular_medias_puntuacion(processed_data['processed_respuestas_forms_pre.csv'], df_grupos)

print(tabla_medias_pre)
print(tabla_medias_post)

shape: (2, 7)
┌─────────┬──────────────┬───────────────┬───────────────┬───────────────┬──────────┬──────────────┐
│ periodo ┆ grupo        ┆ media_tc_gene ┆ media_tc_rete ┆ media_tc_tran ┆ media_ta ┆ media_indice │
│ ---     ┆ ---          ┆ ral           ┆ ncion         ┆ sferencia     ┆ ---      ┆ _desempeño_g │
│ str     ┆ str          ┆ ---           ┆ ---           ┆ ---           ┆ f64      ┆ lobal        │
│         ┆              ┆ f64           ┆ f64           ┆ f64           ┆          ┆ ---          │
│         ┆              ┆               ┆               ┆               ┆          ┆ f32          │
╞═════════╪══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════╪══════════════╡
│ pre     ┆ control      ┆ 0.63          ┆ 0.7           ┆ 0.56          ┆ 0.43     ┆ 1.9          │
│ pre     ┆ experimental ┆ 0.59          ┆ 0.67          ┆ 0.5           ┆ 0.45     ┆ 1.9          │
└─────────┴──────────────┴───────────────┴───────────────┴───────────────┴──────────┴──────────────┘
shape: (2, 7)
┌─────────┬──────────────┬───────────────┬───────────────┬───────────────┬──────────┬──────────────┐
│ periodo ┆ grupo        ┆ media_tc_gene ┆ media_tc_rete ┆ media_tc_tran ┆ media_ta ┆ media_indice │
│ ---     ┆ ---          ┆ ral           ┆ ncion         ┆ sferencia     ┆ ---      ┆ _desempeño_g │
│ str     ┆ str          ┆ ---           ┆ ---           ┆ ---           ┆ f64      ┆ lobal        │
│         ┆              ┆ f64           ┆ f64           ┆ f64           ┆          ┆ ---          │
│         ┆              ┆               ┆               ┆               ┆          ┆ f32          │
╞═════════╪══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════╪══════════════╡
│ post    ┆ control      ┆ 0.8           ┆ 0.82          ┆ 0.78          ┆ 0.51     ┆ 1.92         │
│ post    ┆ experimental ┆ 0.74          ┆ 0.74          ┆ 0.73          ┆ 0.5      ┆ 1.77         │
└─────────┴──────────────┴───────────────┴───────────────┴───────────────┴──────────┴──────────────┘

In [17]:
# 1. Evaluar el Conocimiento General (Hipótesis Principal)
df_tc, mod_tc = realizar_analisis_hake_normalizado(df_cruzado, constructo_base='puntuacion_tc')

# 2. Evaluar el Conocimiento de Retención 
df_ret, mod_ret = realizar_analisis_hake_normalizado(df_cruzado, constructo_base='puntuacion_tc_retencion')

# 3. Evaluar el Conocimiento de Transferencia 
df_transf, mod_transf = realizar_analisis_hake_normalizado(df_cruzado, constructo_base='puntuacion_tc_transferencia')

# 4. Evaluar la mejora en autoeficacia
df_ta, mod_ta = realizar_analisis_hake_normalizado(df_cruzado, constructo_base='puntuacion_ta')

============================================================
 ANÁLISIS DE GANANCIA DE HAKE: PUNTUACION_TC
============================================================
Sujetos excluidos por efecto techo (Pre = 1.0): 6

--- 1. Homogeneidad Inicial (Pre-test) ---
T-test Pre-test: t = 0.884, p-valor = 0.378
-> Grupos HOMOGÉNEOS en el Pre-test.

--- 2. Contraste Principal (Variable g) ---
Normalidad (Shapiro): Control p=0.000, Exp p=0.000 -> Falla
Homocedasticidad (Levene): p=0.602 -> Cumple
=> Aplicando U de Mann-Whitney no paramétrico (H1: Exp > Control)
Resultado Contraste: estadístico = 4990.500, p-valor (unilateral) = 0.976
Tamaño del Efecto (d de Cohen): -0.239

--- 3. Contraste Complementario (ANCOVA) ---
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.6459      0.047     13.798      0.000       0.554       0.738
G_dummy              -0.0567      0.025     -2.307      0.022      -0.105      -0.008
puntuacion_tc_pre     0.2494      0.071      3.503      0.001       0.109       0.390
=====================================================================================

Efecto del Tratamiento (beta_1): p-valor = 0.0111 (unilateral)
Tamaño del Efecto ANCOVA (Eta Cuadrado Parcial): 0.028


============================================================
 ANÁLISIS DE GANANCIA DE HAKE: PUNTUACION_TC_RETENCION
============================================================
Sujetos excluidos por efecto techo (Pre = 1.0): 39

--- 1. Homogeneidad Inicial (Pre-test) ---
T-test Pre-test: t = -0.634, p-valor = 0.527
-> Grupos HOMOGÉNEOS en el Pre-test.

--- 2. Contraste Principal (Variable g) ---
Normalidad (Shapiro): Control p=0.000, Exp p=0.000 -> Falla
Homocedasticidad (Levene): p=0.130 -> Cumple
=> Aplicando U de Mann-Whitney no paramétrico (H1: Exp > Control)
Resultado Contraste: estadístico = 3485.500, p-valor (unilateral) = 0.991
Tamaño del Efecto (d de Cohen): -0.323

--- 3. Contraste Complementario (ANCOVA) ---
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                       0.7563      0.066     11.373      0.000       0.625       0.888
G_dummy                        -0.0749      0.039     -1.945      0.054      -0.151       0.001
puntuacion_tc_retencion_pre     0.0829      0.101      0.823      0.412      -0.116       0.282
===============================================================================================

Efecto del Tratamiento (beta_1): p-valor = 0.0268 (unilateral)
Tamaño del Efecto ANCOVA (Eta Cuadrado Parcial): 0.025


============================================================
 ANÁLISIS DE GANANCIA DE HAKE: PUNTUACION_TC_TRANSFERENCIA
============================================================
Sujetos excluidos por efecto techo (Pre = 1.0): 7

--- 1. Homogeneidad Inicial (Pre-test) ---
T-test Pre-test: t = 1.036, p-valor = 0.302
-> Grupos HOMOGÉNEOS en el Pre-test.

--- 2. Contraste Principal (Variable g) ---
Normalidad (Shapiro): Control p=0.000, Exp p=0.000 -> Falla
Homocedasticidad (Levene): p=0.983 -> Cumple
=> Aplicando U de Mann-Whitney no paramétrico (H1: Exp > Control)
Resultado Contraste: estadístico = 4592.500, p-valor (unilateral) = 0.848
Tamaño del Efecto (d de Cohen): -0.141

--- 3. Contraste Complementario (ANCOVA) ---
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.6865      0.044     15.596      0.000       0.600       0.773
G_dummy                            -0.0459      0.030     -1.540      0.125      -0.105       0.013
puntuacion_tc_transferencia_pre     0.1844      0.073      2.540      0.012       0.041       0.328
===================================================================================================

Efecto del Tratamiento (beta_1): p-valor = 0.0626 (unilateral)
Tamaño del Efecto ANCOVA (Eta Cuadrado Parcial): 0.013


============================================================
 ANÁLISIS DE GANANCIA DE HAKE: PUNTUACION_TA
============================================================
Sujetos excluidos por efecto techo (Pre = 1.0): 1

--- 1. Homogeneidad Inicial (Pre-test) ---
T-test Pre-test: t = -1.367, p-valor = 0.173
-> Grupos HOMOGÉNEOS en el Pre-test.

--- 2. Contraste Principal (Variable g) ---
Normalidad (Shapiro): Control p=0.000, Exp p=0.000 -> Falla
Homocedasticidad (Levene): p=0.114 -> Cumple
=> Aplicando U de Mann-Whitney no paramétrico (H1: Exp > Control)
Resultado Contraste: estadístico = 5095.000, p-valor (unilateral) = 0.938
Tamaño del Efecto (d de Cohen): -0.242

--- 3. Contraste Complementario (ANCOVA) ---
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.3561      0.029     12.478      0.000       0.300       0.412
G_dummy              -0.0185      0.016     -1.170      0.244      -0.050       0.013
puntuacion_ta_pre     0.3597      0.062      5.837      0.000       0.238       0.481
=====================================================================================

Efecto del Tratamiento (beta_1): p-valor = 0.1218 (unilateral)
Tamaño del Efecto ANCOVA (Eta Cuadrado Parcial): 0.007

In [27]:
media_por_grupo = (
    df_tc
    .group_by("grupo")
    .agg(
        pl.col("g").mean().alias("media_g")
    )
)

print("\nMedia de la ganancia de Hake por grupo en preguntas de comprensión:")
print(media_por_grupo)

Media de la ganancia de Hake por grupo en preguntas de comprensión:
shape: (2, 2)
┌──────────────┬──────────┐
│ grupo        ┆ media_g  │
│ ---          ┆ ---      │
│ str          ┆ f64      │
╞══════════════╪══════════╡
│ control      ┆ 0.402582 │
│ experimental ┆ 0.25062  │
└──────────────┴──────────┘

In [28]:
media_por_grupo = (
    df_transf
    .group_by("grupo")
    .agg(
        pl.col("g").mean().alias("media_g")
    )
)

print("\nMedia de la ganancia de Hake por grupo en preguntas de transferencia:")
print(media_por_grupo)

Media de la ganancia de Hake por grupo en preguntas de transferencia:
shape: (2, 2)
┌──────────────┬──────────┐
│ grupo        ┆ media_g  │
│ ---          ┆ ---      │
│ str          ┆ f64      │
╞══════════════╪══════════╡
│ control      ┆ 0.473408 │
│ experimental ┆ 0.402105 │
└──────────────┴──────────┘

In [29]:
media_por_grupo = (
    df_ret
    .group_by("grupo")
    .agg(
        pl.col("g").mean().alias("media_g")
    )
)

print("\nMedia de la ganancia de Hake por grupo en preguntas de retención:")
print(media_por_grupo)

Media de la ganancia de Hake por grupo en preguntas de retención:
shape: (2, 2)
┌──────────────┬──────────┐
│ grupo        ┆ media_g  │
│ ---          ┆ ---      │
│ str          ┆ f64      │
╞══════════════╪══════════╡
│ control      ┆ 0.426329 │
│ experimental ┆ 0.12751  │
└──────────────┴──────────┘

# Análisis diferencias por centros

In [30]:
df_completo_centros, tabla_resumen_centros = analyze_experiment_results_centros(processed_data, hashes_dir)

print("--- TABLA DE MÉTRICAS ---")
print(tabla_resumen_centros)

--- TABLA DE MÉTRICAS ---
shape: (16, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ centro ┆ period ┆ grupo  ┆ puntu ┆ puntu ┆ puntu ┆ puntu ┆ indic ┆ indic ┆ puntu ┆ puntu ┆ indic │
│ ---    ┆ o      ┆ ---    ┆ acion ┆ acion ┆ acion ┆ acion ┆ e_des ┆ e_des ┆ acion ┆ acion ┆ e_des │
│ str    ┆ ---    ┆ str    ┆ _tc_m ┆ _tc_s ┆ _ta_m ┆ _ta_s ┆ empeñ ┆ empeñ ┆ _tc_v ┆ _ta_v ┆ empeñ │
│        ┆ str    ┆        ┆ edia  ┆ td    ┆ edia  ┆ td    ┆ o_glo ┆ o_glo ┆ ar_%  ┆ ar_%  ┆ o_glo │
│        ┆        ┆        ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ bal_m ┆ bal_s ┆ ---   ┆ ---   ┆ bal_v │
│        ┆        ┆        ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ edia  ┆ td    ┆ f64   ┆ f64   ┆ ar_%  │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆ ---   ┆ ---   ┆       ┆       ┆ ---   │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆ f32   ┆ f32   ┆       ┆       ┆ f32   │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ JesusM ┆ post   ┆ contro ┆ 0.79  ┆ 0.17  ┆ 0.52  ┆ 0.09  ┆ 1.96  ┆ 0.62  ┆ 17.91 ┆ 15.56 ┆ -5.31 │
│ aria   ┆        ┆ l      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ JesusM ┆ post   ┆ experi ┆ 0.7   ┆ 0.2   ┆ 0.55  ┆ 0.12  ┆ 1.92  ┆ 0.51  ┆ 18.64 ┆ 17.02 ┆ -4.95 │
│ aria   ┆        ┆ mental ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ JesusM ┆ pre    ┆ contro ┆ 0.67  ┆ 0.2   ┆ 0.45  ┆ 0.15  ┆ 2.07  ┆ 0.49  ┆ null  ┆ null  ┆ null  │
│ aria   ┆        ┆ l      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ JesusM ┆ pre    ┆ experi ┆ 0.59  ┆ 0.17  ┆ 0.47  ┆ 0.11  ┆ 2.02  ┆ 0.49  ┆ null  ┆ null  ┆ null  │
│ aria   ┆        ┆ mental ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ JoseGa ┆ post   ┆ contro ┆ 0.91  ┆ 0.09  ┆ 0.58  ┆ 0.07  ┆ 2.43  ┆ 0.47  ┆ 42.19 ┆ 13.73 ┆ 13.55 │
│ rciaNi ┆        ┆ l      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ eto    ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ …      ┆ …      ┆ …      ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     │
│ Laguna ┆ pre    ┆ experi ┆ 0.49  ┆ 0.18  ┆ 0.39  ┆ 0.11  ┆ 1.46  ┆ 0.45  ┆ null  ┆ null  ┆ null  │
│        ┆        ┆ mental ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Ramiro ┆ post   ┆ contro ┆ 0.83  ┆ 0.11  ┆ 0.49  ┆ 0.1   ┆ 1.85  ┆ 0.59  ┆ 38.33 ┆ 28.95 ┆ 9.47  │
│ Maeztu ┆        ┆ l      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Ramiro ┆ post   ┆ experi ┆ 0.78  ┆ 0.14  ┆ 0.45  ┆ 0.1   ┆ 1.62  ┆ 0.55  ┆ 21.88 ┆ -2.17 ┆ -19.0 │
│ Maeztu ┆        ┆ mental ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Ramiro ┆ pre    ┆ contro ┆ 0.6   ┆ 0.16  ┆ 0.38  ┆ 0.12  ┆ 1.69  ┆ 0.6   ┆ null  ┆ null  ┆ null  │
│ Maeztu ┆        ┆ l      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Ramiro ┆ pre    ┆ experi ┆ 0.64  ┆ 0.15  ┆ 0.46  ┆ 0.13  ┆ 2.0   ┆ 0.62  ┆ null  ┆ null  ┆ null  │
│ Maeztu ┆        ┆ mental ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [32]:
df_g, resumen_centros = realizar_analisis_hake_por_centro(
    df_cruzado,
    constructo_base="puntuacion_tc"
)

print(resumen_centros)

======================================================================
 ANÁLISIS DE HAKE POR CENTRO: PUNTUACION_TC
======================================================================
shape: (4, 9)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ centro   ┆ n_contro ┆ n_experi ┆ media_g_ ┆ media_g_ ┆ test     ┆ estadist ┆ p_valor  ┆ d_cohen  │
│ ---      ┆ l        ┆ mental   ┆ control  ┆ experime ┆ ---      ┆ ico      ┆ ---      ┆ ---      │
│ str      ┆ ---      ┆ ---      ┆ ---      ┆ ntal     ┆ str      ┆ ---      ┆ f64      ┆ f64      │
│          ┆ i64      ┆ i64      ┆ f64      ┆ ---      ┆          ┆ f64      ┆          ┆          │
│          ┆          ┆          ┆          ┆ f64      ┆          ┆          ┆          ┆          │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ JesusMar ┆ 26       ┆ 25       ┆ 0.153022 ┆ 0.202095 ┆ mann-whi ┆ 349.5    ┆ 0.682197 ┆ 0.071247 │
│ ia       ┆          ┆          ┆          ┆          ┆ tney     ┆          ┆          ┆          │
│ JoseGarc ┆ 13       ┆ 14       ┆ 0.796154 ┆ 0.398554 ┆ mann-whi ┆ 144.5    ┆ 0.995887 ┆ -0.96595 │
│ iaNieto  ┆          ┆          ┆          ┆          ┆ tney     ┆          ┆          ┆ 5        │
│ Laguna   ┆ 19       ┆ 25       ┆ 0.23797  ┆ 0.226762 ┆ mann-whi ┆ 209.5    ┆ 0.256822 ┆ -0.01691 │
│          ┆          ┆          ┆          ┆          ┆ tney     ┆          ┆          ┆ 6        │
│ RamiroMa ┆ 31       ┆ 32       ┆ 0.547734 ┆ 0.242448 ┆ mann-whi ┆ 622.5    ┆ 0.960242 ┆ -0.49594 │
│ eztu     ┆          ┆          ┆          ┆          ┆ tney     ┆          ┆          ┆ 1        │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

Observamos como hay un individuo que ha obtenido un 10 en el cuestionario pre. Por lo que se excluye del calculo de la ganancia de Hake o del análisis del impacto de cohen.